[project]
name = "ocr"
version = "0.2.0"
authors = [
    { name = "Leonard Tulipan", email = "leo@leotulipan.at" }
]
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "loguru>=0.7.3",
    "mistralai>=1.9.9",
    "pydantic-settings>=2.10.1",
    "python-dotenv>=1.0.1",
    "pyyaml>=6.0",
    "requests>=2.32.3",
    "rich>=14.1.0",
    "typer>=0.16.1",
]

[project.scripts]
ocr = "ocr.main:app"

[tool.hatch.build.targets.wheel]
packages = ["src/ocr"]

[dependency-groups]
dev = [
    "build>=1.3.0",
]
